name: Build and Test

on:
  push:
    branches:
      - master  # Customize this to your main branch

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 # Specify your desired Python version

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate virtual environment
      run: source venv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt  # Adjust this based on your project setup
  
    - name: Install pytest
      run: python -m pip install pytest

    - name: Test with pytest
      run: | 
        python3 manage.py makemigrations
        python3 manage.py migrate  
        python3 manage.py test

    - name: Send Success Rate to Compass
      run: |
       curl -X POST -H "Authorization: Bearer $COMPASS_API_TOKEN" -H "Content-Type: application/json" \
       -d '{
       "componentId": "ari:cloud:compass:50eeb54a-bd4a-467a-ae53-532574431702:component/5ec6ba4f-632a-4bd6-81bc-2c0ce8b035bf/742a514b-0798-4bc2-9ca8-a2477fc37f48",
       "metricDefinitionId": "ari:cloud:compass::metric-definition/builtin/build-success-rate",
       "externalMetricSourceId": "github-actions",
       "successRate": "95%",  // Modify this to reflect your actual success rate
       "derived": true
       }' \
       https://cybagejanshreya.atlassian.net/compass/metric/predefined/build-success-rate
      env:
       COMPASS_API_TOKEN: ATATT3xFfGF0nkx2lLNloesDaKq13c62XzyTcRb8anrUa66Z_q7vzlarj1Ij4K33Qwf9fdpWMHaLO1WQQkDgyZ7mbLkeKdaeESWa_l2Z1AbR9Qz7kClC6yFkMl6TtOr2ydAT9SM8iYnGO9ivu25XYputergaakxFjcAjFRyqitlYFZlzpbHLPgU=58967857

        
